import { useEffect, useState } from "react";
import { createComplianceCheck, getComplianceChecks } from "../api/securityOpsApi";
import "./SecurityModule.css";

const empty={framework:"PCI DSS",controlId:"",controlName:"",status:"COMPLIANT",remarks:""};
const badge=v=>`badge ${(v||"").toLowerCase()}`;
export default function Compliance(){
 const [items,setItems]=useState([]),[form,setForm]=useState(empty),[show,setShow]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setError("");try{setItems((await getComplianceChecks()).data||[])}catch(e){console.error(e);setError("Unable to load compliance checks.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();setSaving(true);try{await createComplianceCheck(form);setForm(empty);setShow(false);await load()}catch(e){console.error(e);setError("Unable to create compliance check.")}finally{setSaving(false)}};
 return <div className="module-page"><div className="module-heading"><div><div className="eyebrow">AUDIT & COMPLIANCE</div><h1>Compliance</h1><p>Track framework controls and compliance verification.</p></div><div className="module-actions"><button className="module-button secondary" onClick={load}>↻ Refresh</button><button className="module-button" onClick={()=>setShow(v=>!v)}>+ New Check</button></div></div>{error&&<div className="module-error">{error}</div>}{show&&<form className="module-card module-form" onSubmit={submit}><div className="module-field"><label>Framework</label><input required value={form.framework} onChange={e=>setForm({...form,framework:e.target.value})}/></div><div className="module-field"><label>Control ID</label><input required value={form.controlId} onChange={e=>setForm({...form,controlId:e.target.value})} placeholder="A-01"/></div><div className="module-field"><label>Control Name</label><input required value={form.controlName} onChange={e=>setForm({...form,controlName:e.target.value})} placeholder="Access Control"/></div><div className="module-field"><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{["COMPLIANT","NON_COMPLIANT","REVIEW_REQUIRED"].map(x=><option key={x}>{x}</option>)}</select></div><div className="module-field full"><label>Remarks</label><textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})} placeholder="Verification notes..."/></div><div className="form-submit"><button className="module-button" disabled={saving}>{saving?"Saving...":"Create Check"}</button></div></form>}<div className="module-card"><div className="module-toolbar"><div><h2>Compliance Controls</h2><span className="module-count">{items.length} checks</span></div></div><div className="module-table-wrap"><table className="module-table"><thead><tr><th>FRAMEWORK</th><th>CONTROL</th><th>CONTROL NAME</th><th>STATUS</th><th>REMARKS</th><th>CHECKED</th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="empty-module">Loading compliance checks...</td></tr>:items.length===0?<tr><td colSpan="6" className="empty-module">No compliance checks found.</td></tr>:items.map(x=><tr key={x.id}><td><strong>{x.framework}</strong></td><td>{x.controlId}</td><td>{x.controlName}</td><td><span className={badge(x.status)}>{x.status?.replace("_"," ")}</span></td><td>{x.remarks||"—"}</td><td>{x.checkedAt?new Date(x.checkedAt).toLocaleString():"—"}</td></tr>)}</tbody></table></div></div></div>;
}
