import { useEffect, useState } from "react";
import { createVulnerability, getVulnerabilities, markVulnerabilityPatched } from "../api/securityOpsApi";
import "./SecurityModule.css";

const empty = { cveId:"", title:"", affectedSystem:"", severity:"MEDIUM", riskScore:"", description:"", patchVersion:"" };
const badge = (value) => `badge ${(value || "").toLowerCase()}`;

export default function Vulnerabilities(){
 const [items,setItems]=useState([]),[form,setForm]=useState(empty),[show,setShow]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setError("");try{setItems((await getVulnerabilities()).data||[])}catch(e){console.error(e);setError("Unable to load vulnerabilities.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();setSaving(true);try{await createVulnerability({...form,riskScore:form.riskScore===""?null:Number(form.riskScore)});setForm(empty);setShow(false);await load()}catch(e){console.error(e);setError("Unable to create vulnerability.")}finally{setSaving(false)}};
 const patch=async id=>{try{await markVulnerabilityPatched(id);await load()}catch(e){console.error(e);setError("Unable to update patch status.")}};
 return <div className="module-page"><div className="module-heading"><div><div className="eyebrow">RISK MANAGEMENT</div><h1>Vulnerabilities</h1><p>Register CVEs, assess risk and track remediation.</p></div><div className="module-actions"><button className="module-button secondary" onClick={load}>↻ Refresh</button><button className="module-button" onClick={()=>setShow(v=>!v)}>+ New Vulnerability</button></div></div>
 {error&&<div className="module-error">{error}</div>}
 {show&&<form className="module-card module-form" onSubmit={submit}><div className="module-field"><label>CVE ID</label><input required value={form.cveId} onChange={e=>setForm({...form,cveId:e.target.value})} placeholder="CVE-2026-0001"/></div><div className="module-field"><label>Title</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Sample Vulnerability"/></div><div className="module-field"><label>Affected System</label><input value={form.affectedSystem} onChange={e=>setForm({...form,affectedSystem:e.target.value})} placeholder="API Server"/></div><div className="module-field"><label>Severity</label><select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}>{["LOW","MEDIUM","HIGH","CRITICAL"].map(x=><option key={x}>{x}</option>)}</select></div><div className="module-field"><label>Risk Score</label><input type="number" min="0" max="10" step="0.1" value={form.riskScore} onChange={e=>setForm({...form,riskScore:e.target.value})} placeholder="8.2"/></div><div className="module-field"><label>Patch Version</label><input value={form.patchVersion} onChange={e=>setForm({...form,patchVersion:e.target.value})} placeholder="2.1.0"/></div><div className="module-field full"><label>Description</label><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="form-submit"><button className="module-button" disabled={saving}>{saving?"Creating...":"Create Vulnerability"}</button></div></form>}
 <div className="module-card"><div className="module-toolbar"><div><h2>Vulnerability Register</h2><span className="module-count">{items.length} findings</span></div></div><div className="module-table-wrap"><table className="module-table"><thead><tr><th>CVE</th><th>TITLE</th><th>SYSTEM</th><th>SEVERITY</th><th>RISK</th><th>PATCH</th><th>ACTION</th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="empty-module">Loading vulnerabilities...</td></tr>:items.length===0?<tr><td colSpan="7" className="empty-module">No vulnerabilities found.</td></tr>:items.map(x=><tr key={x.id}><td><strong>{x.cveId}</strong></td><td>{x.title}</td><td>{x.affectedSystem||"—"}</td><td><span className={badge(x.severity)}>{x.severity}</span></td><td>{x.riskScore ?? "—"}</td><td><span className={badge(x.patchStatus)}>{x.patchStatus}</span></td><td>{x.patchStatus!=="PATCHED"?<button className="inline-action" onClick={()=>patch(x.id)}>Mark Patched</button>:"✓"}</td></tr>)}</tbody></table></div></div></div>;
}
