package com.infosys.sentinelcorebackend.service;

import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.MailException;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class NotificationService {

    private static final Logger logger = LoggerFactory.getLogger(NotificationService.class);

    private final JavaMailSender mailSender;

    @Value("${alert.recipient-email:}")
    private String recipient;

    public void sendAlertEmail(String assetName, String severity, String message) {
        if (recipient == null || recipient.isBlank()) {
            logger.warn("ALERT_RECIPIENT_EMAIL is not configured. Email notification skipped.");
            return;
        }

        String subject = "[SentinelCore] " + severity + " Security Alert - " + assetName;
        String body = """
                SentinelCore Security Monitoring System
                ========================================

                SECURITY ALERT

                Asset       : %s
                Severity    : %s
                Status      : OPEN

                Alert Details
                -------------
                %s

                This alert was automatically generated by SentinelCore
                Security Monitoring System.

                Please review the affected asset and take appropriate
                action if required.

                ----------------------------------------
                SentinelCore Security Platform
                """.formatted(assetName, severity, message);

        SimpleMailMessage mail = new SimpleMailMessage();
        mail.setTo(recipient);
        mail.setSubject(subject);
        mail.setText(body);

        try {
            mailSender.send(mail);
            logger.info("Alert email sent successfully for asset: {}", assetName);
        } catch (MailException exception) {
            logger.error("Failed to send alert email for asset: {}", assetName, exception);
        }
    }
}
