package com.infosys.sentinelcorebackend.service;


import com.twilio.Twilio;
import com.twilio.rest.api.v2010.account.Message;
import com.twilio.type.PhoneNumber;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class NotificationService {

    private final JavaMailSender mailSender;

    @Value("${alert.recipient.email}")
    private String defaultEmailRecipient;

    @Value("${twilio.account-sid}")
    private String twilioAccountSid;

    @Value("${twilio.auth-token}")
    private String twilioAuthToken;

    @Value("${twilio.from-number}")
    private String twilioFromNumber;

    @Value("${alert.recipient.phone}")
    private String defaultPhoneRecipient;

    @PostConstruct
    public void initializeTwilio() {
        Twilio.init(twilioAccountSid, twilioAuthToken);
    }

    public void sendAlertEmail(
            String toEmail,
            String assetName,
            String severity,
            String message
    ) {
        String recipient =
                (toEmail == null || toEmail.isBlank())
                        ? defaultEmailRecipient
                        : toEmail;

        SimpleMailMessage mail = new SimpleMailMessage();

        mail.setTo(recipient);
        mail.setSubject(
                "[SentinelCore] " + severity +
                        " Security Alert - " + assetName
        );

        mail.setText(
                "SentinelCore Security Monitoring System\n\n" +
                        "SECURITY ALERT\n\n" +
                        "Asset    : " + assetName + "\n" +
                        "Severity : " + severity + "\n" +
                        "Status   : OPEN\n\n" +
                        "Alert Details\n" +
                        "-------------\n" +
                        message + "\n\n" +
                        "This alert was automatically generated by SentinelCore."
        );

        mailSender.send(mail);
    }

    public void sendAlertSms(
            String phoneNumber,
            String assetName,
            String severity,
            String message
    ) {
        String recipient =
                (phoneNumber == null || phoneNumber.isBlank())
                        ? defaultPhoneRecipient
                        : phoneNumber;

        String smsBody =
                "[SentinelCore] " + severity +
                        " ALERT\nAsset: " + assetName +
                        "\nDetails: " + message;

        Message.creator(
                new PhoneNumber(recipient),
                new PhoneNumber(twilioFromNumber),
                smsBody
        ).create();
    }

    public void sendAlertNotifications(
            String assetName,
            String severity,
            String message
    ) {
        sendAlertEmail(
                defaultEmailRecipient,
                assetName,
                severity,
                message
        );

        sendAlertSms(
                defaultPhoneRecipient,
                assetName,
                severity,
                message
        );
    }
}