spring.application.name=sentinel-core-backend

# ==========================================
# PostgreSQL Database
# ==========================================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/sentinelcore}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:yjserver19}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080


# ==========================================
# JWT Configuration
# ==========================================
jwt.secret=${JWT_SECRET:SentinelCoreLocalJwtSecretKeyChangeMe2026!}


# ==========================================
# Email Notification Configuration
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.test-connection=false

alert.recipient.email=${ALERT_RECIPIENT_EMAIL}


# ==========================================
# Twilio SMS Notification Configuration
# ==========================================
twilio.enabled=${TWILIO_ENABLED:false}
twilio.account-sid=${TWILIO_ACCOUNT_SID:}
twilio.auth-token=${TWILIO_AUTH_TOKEN:}
twilio.from-number=${TWILIO_FROM_NUMBER:}

alert.recipient.phone=${ALERT_RECIPIENT_PHONE:}